/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ExperienceIndexRouteImport } from './routes/experience/index'
import { Route as ExperienceIdRouteImport } from './routes/experience/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIdRoute = ExperienceIdRouteImport.update({
  id: '/experience/$id',
  path: '/experience/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experience/$id': typeof ExperienceIdRoute
  '/contact/': typeof ContactIndexRoute
  '/experience/': typeof ExperienceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience/$id': typeof ExperienceIdRoute
  '/contact': typeof ContactIndexRoute
  '/experience': typeof ExperienceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experience/$id': typeof ExperienceIdRoute
  '/contact/': typeof ContactIndexRoute
  '/experience/': typeof ExperienceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experience/$id' | '/contact/' | '/experience/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experience/$id' | '/contact' | '/experience'
  id: '__root__' | '/' | '/experience/$id' | '/contact/' | '/experience/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceIdRoute: typeof ExperienceIdRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ExperienceIndexRoute: typeof ExperienceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$id': {
      id: '/experience/$id'
      path: '/experience/$id'
      fullPath: '/experience/$id'
      preLoaderRoute: typeof ExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceIdRoute: ExperienceIdRoute,
  ContactIndexRoute: ContactIndexRoute,
  ExperienceIndexRoute: ExperienceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
